const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    price: 10000,
    location: "Fiji",
    country: "Fiji",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Boston",
    country: "United States",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Banff",
    country: "Canada",
  },
  {
    title: "Icelandic Glass Cabin",
    description: "Watch the Northern Lights from the comfort of this glass-roofed cabin in the wilderness.",
    image: "https://assets3.thrillist.com/v1/image/3061466/1584x1056/crop;webp=auto;jpeg_quality=60;progressive.jpg",
    price: 2700,
    location: "Reykjavík",
    country: "Iceland",
  },
  {
    title: "Santorini Cliffside Villa",
    description: "Enjoy the whitewashed beauty of Santorini in this luxurious villa overlooking the caldera.",
    image: "https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 3200,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Traditional Ryokan with Onsen",
    description: "Relax in a private hot spring bath in this serene Japanese inn surrounded by nature.",
    image: "https://i0.wp.com/enjoy-onsen.com/wp-content/uploads/2017/11/Tokinoyu-Setsugetsuka_hakone-onsen-ryokan-3.jpg?w=1024&ssl=1",
    price: 2100,
    location: "Kyoto",
    country: "Japan",
  },
  {
    title: "Elegant Riad in Marrakech",
    description: "Step into a world of colorful mosaics and tranquil courtyards in this elegant Moroccan riad.",
    image: "https://cdn.razola.xyz/p14/i/g-5407fbd635c3d4c698cfda065ab225721d4a8dee66640611cade55b0bb3aad17.webp?z=1589066655#s1500x1000",
    price: 1700,
    location: "Marrakech",
    country: "Morocco",
  },
  {
    title: "Floating Villa in the Maldives",
    description: "Sleep above crystal-clear waters in this stunning overwater villa with direct ocean access.",
    image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 6000,
    location: "Baa Atoll",
    country: "Maldives",
  },
  {
    title: "Countryside Farm Stay",
    description: "Reconnect with nature on this working farm offering fresh produce and cozy accommodations.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 700,
    location: "Devon",
    country: "United Kingdom",
  },
  {
    title: "Colorful Casa in Cartagena",
    description: "Live among vibrant colonial architecture in this charming Caribbean townhome.",
    image: "https://cdn.prod.website-files.com/66081f2593f055261bf2b390/668992dc7c97c204e213cb2f_home_hero_01.jpg",
    price: 1300,
    location: "Cartagena",
    country: "Colombia",
  },
  {
    title: "Art Deco Apartment in Paris",
    description: "Enjoy the romantic ambiance of Paris from this tastefully restored Art Deco apartment.",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Paris",
    country: "France",
  },
  {
    title: "Scandinavian Cabin Escape",
    description: "A minimalistic retreat surrounded by pine forests and snowy peaks in northern Sweden.",
    image: "https://i0.wp.com/mossandfog.com/wp-content/uploads/2017/01/snohetta-tree-hotel-7th-room-sweden-mossandfog-6.jpg?resize=750%2C500&quality=89&ssl=1",
    price: 1900,
    location: "Abisko",
    country: "Sweden",
  },
  {
    title: "Bohemian Dome in the Desert",
    description: "Unplug under the stars in this artistic dome in the heart of the desert.",
    image: "https://www.blessthisstuff.com/imagens/listagem/2019/grande/grande_dome-in-the-desert.jpg",
    price: 1100,
    location: "Joshua Tree",
    country: "United States",
  },
  {
    title: "Lakefront A-Frame Getaway",
    description: "Charming A-frame cabin with a deck right on the lake—ideal for cozy nights and kayaking.",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 950,
    location: "Minnesota",
    country: "United States",
  },
  {
    title: "Eco Lodge in the Amazon",
    description: "Adventure into the jungle while enjoying sustainable luxury in this riverside eco lodge.",
    image: "https://imgs.search.brave.com/-Tm00DttLukvv4oO5ba41RJh0k0U-jxbIqcmW8Oxmbc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/c291dGhhbWVyaWNh/LnRyYXZlbC93cC1j/b250ZW50L3czLXdl/YnAvdXBsb2Fkcy8y/MDE5LzA5L2FtYXpv/bi1sb2RnZS5qcGd3/My53ZWJw",
    price: 2200,
    location: "Manaus",
    country: "Brazil",
  },
  {
    title: "Vineyard Villa in Napa Valley",
    description: "Wake up to vineyard views and wine tastings in this luxurious Napa Valley retreat.",
    image: "https://www.theestateyountville.com/wp-content/uploads/2021/05/00_TheVilla-atTheEstate_Primary-1680x946.jpg",
    price: 3100,
    location: "Napa",
    country: "United States",
  },
  {
    title: "Igloo Experience in Finland",
    description: "Sleep in a thermal glass igloo under the stars and northern lights in Lapland.",
    image: "https://imgs.search.brave.com/CCsBJceIyGMmxWLdzWCJZ0WlLHV1sXK9EgFG54ObRMQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pZ2xv/b2hvdGVscy5maS93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyNC8x/MC9zYW50YS1pZ2xv/b3MtYXJ0aWMtY2ly/Y2xlLmpwZw",
    price: 3300,
    location: "Rovaniemi",
    country: "Finland",
  }
];


export default { data: sampleListings };
